#!/bin/bash
# This script displays the first 10 lines of the /etc/passwd file.
# The /etc/passwd file contains user account information.
# The 'head' command is used to output the first part of files.
# The '-n 10' option specifies that the first 10 lines should be displayed.
head -n 10 /etc/passwd

