#!/bin/bash
# This script reads input line by line and prints only the odd-numbered lines.
# It uses Perl with the -l and -n options:
# - The -l option automatically chomps the input line and appends a newline to the output.
# - The -n option loops over the input line by line.
# The script checks if the current line number ($.) is odd (using $. % 2 == 1) and prints it if true.
perl -lne 'print if $. % 2 ==1'
