#!/bin/bash
# This script changes the owner and group of the symbolic link "_hello" to "vincent" and "staff" respectively.
# The -h option ensures that the ownership change is applied to the symbolic link itself, not the target file it points to.
chown -h vincent:staff _hello
