#!/bin/bash
# This script copies all HTML files from the current directory to the parent directory.
# Options used with 'cp' command:
# -r: Recursively copy directories and their contents.
# -u: Copy only when the source file is newer than the destination file or when the destination file is missing.
# -a: Archive mode; same as -dR --preserve=all, which preserves the structure and attributes of files.
cp -rua *.html ../
